[[server]]

listen =				"8080"
host =					"127.0.0.1"
server_names =			"localhost"
client_max_body_size =	"1MB"
auto_index =			"false"

	[server.error_pages]

	400 = "html/BadRequest.html"
	401 = "html/unauthorized.html"
	403 = "html/forbidden.html"
	404 = "html/PageNotFound.html"
	405 = "html/MethodNotAllowed.html"
	406 = "html/NotAcceptable.html"
	407 = "html/ProxyAuthenticationRequired.html"
	408 = "html/RequestTimeout.html"
	409 = "html/Conflict.html"
	411 = "html/LengthRequired.html"
	413 = "html/PayloadTooLarge.html"
	414 = "html/URITooLong.html"
	415 = "html/UnsupportedMediaType.html"
	431 = "html/RequestHeaderFieldsTooLarge.html"
	500 = "html/InternalServerError.html"
	501 = "html/NotImplemented.html"
	502 = "html/BadGateway.html"
	503 = "html/ServiceUnavailable.html"
	504 = "html/GatewayTimeout.html"
	505 = "html/HTTPVersionNotSupported.html"
	507 = "html/InsufficientStorage.html"
	508 = "html/LoopDetected.html"
	511 = "html/NetworkAuthenticationRequired.html"

	[[server.location]]

	match =				"/"
	allowed_methods =	"GET"
	root =				"html/"
	index =				"home.html"

	[[server.location]]

	match =				"/cgi-bin"
	allowed_methods =	["POST", "DELETE"]
	root =				"cgi-bin/"
	index =				"upload.py"
	cgi_extents =		".py"
	cgi_paths =			"/usr/bin/python3"
