#!/usr/bin/python3

import os

print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("    <meta charset='utf-8'>")
print("    <meta name='viewport' content='width=device-width, initial-scale=1'>")
print("    <title>Webserv</title>")
print("    <link rel='icon' type='image/x-icon' href='/html/images/favicon.ico'>")
print("    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH' crossorigin='anonymous'>")
print("    <link href='/html/css/stylesheet.css' rel='stylesheet' type='text/css'>")
print("    <style>")
print("        body {")
print("            background-color: #f8f9fa;")
print("        }")
print("        .navigation-bar {")
print("            background-color: #b097f5;")
print("            padding: 10px;")
print("        }")
print("        .navigation-bar a {")
print("            color: #fff;")
print("            margin-right: 15px;")
print("            text-decoration: none;")
print("        }")
print("        .hero {")
print("            background: url('/html/images/codam.jpg') no-repeat center center;")
print("            background-size: cover;")
print("            color: white;")
print("            height: 100vh;")
print("            display: flex;")
print("            justify-content: center;")
print("            align-items: center;")
print("            flex-direction: column;")
print("        }")
print("        .hero h2 {")
print("            font-size: 3rem;")
print("            font-weight: bold;")
print("            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);")
print("            margin-bottom: 20px;")
print("        }")
print("        .files-block {")
print("            background: rgba(255, 255, 255, 0.9);")
print("            padding: 20px;")
print("            border-radius: 8px;")
print("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);")
print("            width: 100%;")
print("            max-width: 800px;")
print("        }")
print("        .entry {")
print("            display: flex;")
print("            justify-content: space-between;")
print("            align-items: center;")
print("            padding: 10px;")
print("            border-bottom: 1px solid #ddd;")
print("        }")
print("        .delete-button {")
print("            background-color: #ff4d4d;")
print("            border: none;")
print("            color: #fff;")
print("            padding: 5px 10px;")
print("            border-radius: 4px;")
print("            cursor: pointer;")
print("        }")
print("        .delete-button:hover {")
print("            background-color: #e60000;")
print("        }")
print("        .file-name {")
print("            color: #000;")
print("        }")
print("        .no-files {")
print("            color: #333;")
print("            font-size: 1.2rem;")
print("            text-align: center;")
print("            padding: 20px 0;")
print("        }")
print("    </style>")
print("</head>")
print("<body>")

print("    <nav class='navigation-bar'>")
print("        <a href='/'>Home</a>")
print("        <a href='/html/version2/newupload.html'>Upload</a>")
print("        <a href='/cgi-bin/newshowUploads.py'>Files</a>")
print("        <a href='/html/version2/newtests.html'>Tests</a>")
print("    </nav>")

print("    <div class='hero'>")
print("        <h2>Uploaded files</h2>")
print("        <div class='files-block'>")
print("            <ul>")

cwd = os.getcwd()
sub_dir = 'uploads'
upload_dir = os.path.join(cwd, sub_dir)

if os.path.exists(upload_dir) and os.path.isdir(upload_dir):
    count = 0
    for filename in os.listdir(upload_dir):
        display_filename = filename.replace('%20', ' ')
        line = "<div class='entry'><button class='delete-button' value='"
        line += filename
        line += "' onclick='deleteFile(\""
        line += filename
        line += "\")'>Delete</button><p class='file-name'>"
        line += display_filename
        line += "</p><br></div>"
        print(line)
        count += 1
    if count == 0:
        print("<p class='no-files'>No files uploaded</p>")
else:
    print("<p class='no-files'>No files uploaded</p>")

print("            </ul>")
print("        </div>")
print("    </div>")

print("    <script>")
print("    function deleteFile(filename) {")
print("        const filePath = 'uploads/' + filename;")
print("        fetch(filePath, {")
print("            method: 'DELETE'")
print("        })")
print("        .then(response => {")
print("            if (response.ok) {")
print("                window.location.reload();")
print("            } else {")
print("                return response.text().then(text => {")
print("                    document.open();")
print("                    document.write(text);")
print("                    document.close();")
print("                });")
print("            }")
print("        })")
print("    }")
print("    </script>")

print("</body>")
print("</html>")
